// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_list_leaderboards_output_output_output(value: &crate::output::ListLeaderboardsOutput) -> Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::protocol_serde::shape_list_leaderboards_output::ser_list_leaderboards_output_output(&mut object, value)?;
    object.finish();
    Ok(out)
}

pub fn ser_list_leaderboards_output_output(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::output::ListLeaderboardsOutput,
                    ) -> Result<(), ::aws_smithy_types::error::operation::SerializationError> {
    if let Some(var_1) = &input.leaderboards {
        let mut array_2 = object.key("leaderboards").start_array();
        for item_3 in var_1 {
             {
                #[allow(unused_mut)]
                let mut object_4 = array_2.value().start_object();
                crate::protocol_serde::shape_leaderboard_summary::ser_leaderboard_summary(&mut object_4, item_3)?;
                object_4.finish();
            }
        }
        array_2.finish();
    }
    if let Some(var_5) = &input.next_token {
        object.key("nextToken").string(var_5.as_str());
    }
    Ok(())
}

