// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub fn ser_create_leaderboard_output_output_output(value: &crate::output::CreateLeaderboardOutput) -> Result<String, ::aws_smithy_types::error::operation::SerializationError> {
    let mut out = String::new();
    let mut object = ::aws_smithy_json::serialize::JsonObjectWriter::new(&mut out);
    crate::protocol_serde::shape_create_leaderboard_output::ser_create_leaderboard_output_output(&mut object, value)?;
    object.finish();
    Ok(out)
}

pub fn ser_create_leaderboard_output_output(
                         object: &mut ::aws_smithy_json::serialize::JsonObjectWriter,
                         input: &crate::output::CreateLeaderboardOutput,
                    ) -> Result<(), ::aws_smithy_types::error::operation::SerializationError> {
     {
        object.key("id").string(input.id.as_str());
    }
    Ok(())
}

