// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.endpoints



/**
 * The set of values necessary for endpoint resolution.
 */
public class ElasticLeaderboardEndpointParameters private constructor(builder: Builder) {
    public companion object {
        public inline operator fun invoke(block: Builder.() -> Unit): ElasticLeaderboardEndpointParameters = Builder().apply(block).build()
    }

    public override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is ElasticLeaderboardEndpointParameters) return false
        return true
    }

    public override fun hashCode(): Int {
        return this::class.hashCode()
    }

    public override fun toString(): String = buildString {
        append("ElasticLeaderboardEndpointParameters(")
    }

    public fun copy(block: Builder.() -> Unit = {}): ElasticLeaderboardEndpointParameters {
        return Builder().apply {
            block()
        }
        .build()
    }

    public class Builder {

        public fun build(): ElasticLeaderboardEndpointParameters = ElasticLeaderboardEndpointParameters(this)
    }
}
