// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.endpoints

import aws.smithy.kotlin.runtime.client.endpoints.EndpointProvider

/**
 * Resolves to an endpoint for a given service operation.
 */
public fun interface ElasticLeaderboardEndpointProvider: EndpointProvider<ElasticLeaderboardEndpointParameters>
