// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.model

import aws.smithy.kotlin.runtime.SdkDsl

public class CreateLeaderboardResponse private constructor(builder: Builder) {
    public val id: kotlin.String = requireNotNull(builder.id) { "A non-null value must be provided for id" }

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): kotlinconf.elasticleaderboard.model.CreateLeaderboardResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("CreateLeaderboardResponse(")
        append("id=$id")
        append(")")
    }

    override fun hashCode(): kotlin.Int {
        var result = id.hashCode()
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as CreateLeaderboardResponse

        if (id != other.id) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): kotlinconf.elasticleaderboard.model.CreateLeaderboardResponse = Builder(this).apply(block).build()

    @SdkDsl
    public class Builder {
        public var id: kotlin.String? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: kotlinconf.elasticleaderboard.model.CreateLeaderboardResponse) : this() {
            this.id = x.id
        }

        @PublishedApi
        internal fun build(): kotlinconf.elasticleaderboard.model.CreateLeaderboardResponse = CreateLeaderboardResponse(this)

        internal fun correctErrors(): Builder {
            if (id == null) id = ""
            return this
        }
    }
}
