// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.model

import aws.smithy.kotlin.runtime.SdkDsl

public class CreateLeaderboardRequest private constructor(builder: Builder) {
    public val maxEntries: kotlin.Int? = builder.maxEntries
    public val name: kotlin.String? = builder.name
    public val token: kotlin.String? = builder.token

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): kotlinconf.elasticleaderboard.model.CreateLeaderboardRequest = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("CreateLeaderboardRequest(")
        append("maxEntries=$maxEntries,")
        append("name=$name,")
        append("token=$token")
        append(")")
    }

    override fun hashCode(): kotlin.Int {
        var result = maxEntries ?: 0
        result = 31 * result + (name?.hashCode() ?: 0)
        result = 31 * result + (token?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as CreateLeaderboardRequest

        if (maxEntries != other.maxEntries) return false
        if (name != other.name) return false
        if (token != other.token) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): kotlinconf.elasticleaderboard.model.CreateLeaderboardRequest = Builder(this).apply(block).build()

    @SdkDsl
    public class Builder {
        public var maxEntries: kotlin.Int? = null
        public var name: kotlin.String? = null
        public var token: kotlin.String? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: kotlinconf.elasticleaderboard.model.CreateLeaderboardRequest) : this() {
            this.maxEntries = x.maxEntries
            this.name = x.name
            this.token = x.token
        }

        @PublishedApi
        internal fun build(): kotlinconf.elasticleaderboard.model.CreateLeaderboardRequest = CreateLeaderboardRequest(this)

        internal fun correctErrors(): Builder {
            return this
        }
    }
}
