// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.model

import aws.smithy.kotlin.runtime.SdkDsl

public class DeleteLeaderboardRequest private constructor(builder: Builder) {
    public val id: kotlin.String? = builder.id

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): kotlinconf.elasticleaderboard.model.DeleteLeaderboardRequest = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("DeleteLeaderboardRequest(")
        append("id=$id")
        append(")")
    }

    override fun hashCode(): kotlin.Int {
        var result = id?.hashCode() ?: 0
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as DeleteLeaderboardRequest

        if (id != other.id) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): kotlinconf.elasticleaderboard.model.DeleteLeaderboardRequest = Builder(this).apply(block).build()

    @SdkDsl
    public class Builder {
        public var id: kotlin.String? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: kotlinconf.elasticleaderboard.model.DeleteLeaderboardRequest) : this() {
            this.id = x.id
        }

        @PublishedApi
        internal fun build(): kotlinconf.elasticleaderboard.model.DeleteLeaderboardRequest = DeleteLeaderboardRequest(this)

        internal fun correctErrors(): Builder {
            return this
        }
    }
}
