// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.model

import aws.smithy.kotlin.runtime.SdkDsl

public class LeaderboardSummary private constructor(builder: Builder) {
    public val id: kotlin.String? = builder.id
    public val maxEntries: kotlin.Int? = builder.maxEntries
    public val name: kotlin.String? = builder.name

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): kotlinconf.elasticleaderboard.model.LeaderboardSummary = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("LeaderboardSummary(")
        append("id=$id,")
        append("maxEntries=$maxEntries,")
        append("name=$name")
        append(")")
    }

    override fun hashCode(): kotlin.Int {
        var result = id?.hashCode() ?: 0
        result = 31 * result + (maxEntries ?: 0)
        result = 31 * result + (name?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as LeaderboardSummary

        if (id != other.id) return false
        if (maxEntries != other.maxEntries) return false
        if (name != other.name) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): kotlinconf.elasticleaderboard.model.LeaderboardSummary = Builder(this).apply(block).build()

    @SdkDsl
    public class Builder {
        public var id: kotlin.String? = null
        public var maxEntries: kotlin.Int? = null
        public var name: kotlin.String? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: kotlinconf.elasticleaderboard.model.LeaderboardSummary) : this() {
            this.id = x.id
            this.maxEntries = x.maxEntries
            this.name = x.name
        }

        @PublishedApi
        internal fun build(): kotlinconf.elasticleaderboard.model.LeaderboardSummary = LeaderboardSummary(this)

        internal fun correctErrors(): Builder {
            return this
        }
    }
}
