// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.model

import aws.smithy.kotlin.runtime.SdkDsl

public class ListLeaderboardsResponse private constructor(builder: Builder) {
    public val leaderboards: List<LeaderboardSummary>? = builder.leaderboards
    public val nextToken: kotlin.String? = builder.nextToken

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): kotlinconf.elasticleaderboard.model.ListLeaderboardsResponse = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("ListLeaderboardsResponse(")
        append("leaderboards=$leaderboards,")
        append("nextToken=$nextToken")
        append(")")
    }

    override fun hashCode(): kotlin.Int {
        var result = leaderboards?.hashCode() ?: 0
        result = 31 * result + (nextToken?.hashCode() ?: 0)
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as ListLeaderboardsResponse

        if (leaderboards != other.leaderboards) return false
        if (nextToken != other.nextToken) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): kotlinconf.elasticleaderboard.model.ListLeaderboardsResponse = Builder(this).apply(block).build()

    @SdkDsl
    public class Builder {
        public var leaderboards: List<LeaderboardSummary>? = null
        public var nextToken: kotlin.String? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: kotlinconf.elasticleaderboard.model.ListLeaderboardsResponse) : this() {
            this.leaderboards = x.leaderboards
            this.nextToken = x.nextToken
        }

        @PublishedApi
        internal fun build(): kotlinconf.elasticleaderboard.model.ListLeaderboardsResponse = ListLeaderboardsResponse(this)

        internal fun correctErrors(): Builder {
            return this
        }
    }
}
