// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.model

import aws.smithy.kotlin.runtime.SdkDsl
import aws.smithy.kotlin.runtime.ServiceErrorMetadata

/**
 * A standard error for input validation failures. This should be thrown by services when a member of the input structure falls outside of the modeled or documented constraints.
 */
public class ValidationException private constructor(builder: Builder) : ElasticLeaderboardException(builder.message) {

    /**
     * A list of specific failures encountered while validating the input. A member can appear in this list more than once if it failed to satisfy multiple constraints.
     */
    public val fieldList: List<ValidationExceptionField>? = builder.fieldList

    init {
        sdkErrorMetadata.attributes[ServiceErrorMetadata.ErrorType] = ErrorType.Client
    }

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): kotlinconf.elasticleaderboard.model.ValidationException = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("ValidationException(")
        append("fieldList=$fieldList,")
        append("message=$message")
        append(")")
    }

    override fun hashCode(): kotlin.Int {
        var result = fieldList?.hashCode() ?: 0
        result = 31 * result + (message.hashCode())
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as ValidationException

        if (fieldList != other.fieldList) return false
        if (message != other.message) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): kotlinconf.elasticleaderboard.model.ValidationException = Builder(this).apply(block).build()

    @SdkDsl
    public class Builder {
        /**
         * A list of specific failures encountered while validating the input. A member can appear in this list more than once if it failed to satisfy multiple constraints.
         */
        public var fieldList: List<ValidationExceptionField>? = null
        /**
         * A summary of the validation failure.
         */
        public var message: kotlin.String? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: kotlinconf.elasticleaderboard.model.ValidationException) : this() {
            this.fieldList = x.fieldList
            this.message = x.message
        }

        @PublishedApi
        internal fun build(): kotlinconf.elasticleaderboard.model.ValidationException = ValidationException(this)

        internal fun correctErrors(): Builder {
            if (message == null) message = ""
            return this
        }
    }
}
