// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.model

import aws.smithy.kotlin.runtime.SdkDsl

/**
 * Describes one specific validation failure for an input member.
 */
public class ValidationExceptionField private constructor(builder: Builder) {
    /**
     * A detailed description of the validation failure.
     */
    public val message: kotlin.String = requireNotNull(builder.message) { "A non-null value must be provided for message" }
    /**
     * A JSONPointer expression to the structure member whose value failed to satisfy the modeled constraints.
     */
    public val path: kotlin.String = requireNotNull(builder.path) { "A non-null value must be provided for path" }

    public companion object {
        public operator fun invoke(block: Builder.() -> kotlin.Unit): kotlinconf.elasticleaderboard.model.ValidationExceptionField = Builder().apply(block).build()
    }

    override fun toString(): kotlin.String = buildString {
        append("ValidationExceptionField(")
        append("message=$message,")
        append("path=$path")
        append(")")
    }

    override fun hashCode(): kotlin.Int {
        var result = message.hashCode()
        result = 31 * result + (path.hashCode())
        return result
    }

    override fun equals(other: kotlin.Any?): kotlin.Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as ValidationExceptionField

        if (message != other.message) return false
        if (path != other.path) return false

        return true
    }

    public inline fun copy(block: Builder.() -> kotlin.Unit = {}): kotlinconf.elasticleaderboard.model.ValidationExceptionField = Builder(this).apply(block).build()

    @SdkDsl
    public class Builder {
        /**
         * A detailed description of the validation failure.
         */
        public var message: kotlin.String? = null
        /**
         * A JSONPointer expression to the structure member whose value failed to satisfy the modeled constraints.
         */
        public var path: kotlin.String? = null

        @PublishedApi
        internal constructor()
        @PublishedApi
        internal constructor(x: kotlinconf.elasticleaderboard.model.ValidationExceptionField) : this() {
            this.message = x.message
            this.path = x.path
        }

        @PublishedApi
        internal fun build(): kotlinconf.elasticleaderboard.model.ValidationExceptionField = ValidationExceptionField(this)

        internal fun correctErrors(): Builder {
            if (message == null) message = ""
            if (path == null) path = ""
            return this
        }
    }
}
