// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.auth

import aws.smithy.kotlin.runtime.auth.AuthOption
import aws.smithy.kotlin.runtime.auth.AuthSchemeId
import kotlinconf.elasticleaderboard.endpoints.ElasticLeaderboardEndpointProvider

public class DefaultElasticLeaderboardAuthSchemeProvider(private val endpointProvider: ElasticLeaderboardEndpointProvider? = null) : ElasticLeaderboardAuthSchemeProvider {
    private val operationOverrides = mapOf<String, List<AuthOption>>(
    )
    private val serviceDefaults = listOf<AuthOption>(
        AuthOption(AuthSchemeId.Anonymous),
    )
    override suspend fun resolveAuthScheme(params: ElasticLeaderboardAuthSchemeParameters): List<AuthOption> {
        val modeledAuthOptions = operationOverrides.getOrElse(params.operationName) {
            serviceDefaults
        }
        return modeledAuthOptions
    }
}
