// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.auth



public class ElasticLeaderboardAuthSchemeParameters private constructor(builder: Builder) {
    public val operationName: String = requireNotNull(builder.operationName) { "operationName is a required auth scheme parameter" }
    public companion object {
        public inline operator fun invoke(block: Builder.() -> kotlin.Unit): ElasticLeaderboardAuthSchemeParameters = Builder().apply(block).build()
    }

    public fun toBuilder(): Builder = Builder().apply {
        operationName = this@ElasticLeaderboardAuthSchemeParameters.operationName
    }

    public class Builder {
        /**
         * The name of the operation currently being invoked.
         */
        public var operationName: String? = null

        @PublishedApi
        internal fun build(): ElasticLeaderboardAuthSchemeParameters = ElasticLeaderboardAuthSchemeParameters(this)
    }

    override fun toString(): String = buildString {
        append("ElasticLeaderboardAuthSchemeParameters(")
        append("operationName=$operationName)")
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is ElasticLeaderboardAuthSchemeParameters) return false
        if (this.operationName != other.operationName) return false
        return true
    }

    override fun hashCode(): Int {
        var result = operationName?.hashCode() ?: 0
        return result
    }

    public fun copy(block: Builder.() -> Unit = {}): ElasticLeaderboardAuthSchemeParameters {
        return Builder().apply {
            operationName = this@ElasticLeaderboardAuthSchemeParameters.operationName
            block()
        }
        .build()
    }
}
