// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.auth

import aws.smithy.kotlin.runtime.auth.AuthSchemeProvider

/**
 * ElasticLeaderboardAuthSchemeProvider is responsible for resolving the authentication scheme to use for a particular operation.
 * See [DefaultElasticLeaderboardAuthSchemeProvider] for the default SDK behavior of this interface.
 */
public interface ElasticLeaderboardAuthSchemeProvider : AuthSchemeProvider<ElasticLeaderboardAuthSchemeParameters>
