// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) mod shape_create_leaderboard;

pub(crate) mod shape_delete_leaderboard;

pub(crate) mod shape_get_leaderboard;

pub(crate) mod shape_list_leaderboards;

pub(crate) mod shape_submit_score_event;

pub(crate) mod shape_update_leaderboard;

pub(crate) fn or_empty_doc(data: &[u8]) -> &[u8] {
                    if data.is_empty() {
                        b"{}"
                    } else {
                        data
                    }
                }

pub(crate) mod shape_create_leaderboard_output;

pub(crate) mod shape_delete_leaderboard_input;

pub(crate) mod shape_get_leaderboard_input;

pub(crate) mod shape_get_leaderboard_output;

pub(crate) mod shape_list_leaderboards_input;

pub(crate) mod shape_list_leaderboards_output;

pub(crate) mod shape_not_found_error;

pub(crate) mod shape_submit_score_event_input;

pub(crate) mod shape_update_leaderboard_input;

pub(crate) mod shape_validation_exception;

pub(crate) mod shape_score_event;

pub(crate) mod shape_leaderboard_summary;

pub(crate) mod shape_validation_exception_field;

