// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.serde

import aws.smithy.kotlin.runtime.awsprotocol.json.RestJsonErrorDeserializer
import aws.smithy.kotlin.runtime.awsprotocol.setAseErrorMetadata
import aws.smithy.kotlin.runtime.awsprotocol.withPayload
import aws.smithy.kotlin.runtime.http.HttpCall
import aws.smithy.kotlin.runtime.http.isSuccess
import aws.smithy.kotlin.runtime.http.operation.HttpDeserializer
import aws.smithy.kotlin.runtime.operation.ExecutionContext
import aws.smithy.kotlin.runtime.serde.SdkFieldDescriptor
import aws.smithy.kotlin.runtime.serde.SdkObjectDescriptor
import aws.smithy.kotlin.runtime.serde.SerialKind
import aws.smithy.kotlin.runtime.serde.asSdkSerializable
import aws.smithy.kotlin.runtime.serde.deserializeList
import aws.smithy.kotlin.runtime.serde.deserializeMap
import aws.smithy.kotlin.runtime.serde.deserializeStruct
import aws.smithy.kotlin.runtime.serde.field
import aws.smithy.kotlin.runtime.serde.json.JsonDeserializer
import aws.smithy.kotlin.runtime.serde.json.JsonSerialName
import aws.smithy.kotlin.runtime.serde.serializeList
import aws.smithy.kotlin.runtime.serde.serializeMap
import aws.smithy.kotlin.runtime.serde.serializeStruct
import kotlin.collections.mutableListOf
import kotlinconf.elasticleaderboard.model.ElasticLeaderboardException
import kotlinconf.elasticleaderboard.model.GetLeaderboardResponse
import kotlinconf.elasticleaderboard.model.ScoreEvent


internal class GetLeaderboardOperationDeserializer: HttpDeserializer.NonStreaming<GetLeaderboardResponse> {

    override fun deserialize(context: ExecutionContext, call: HttpCall, payload: ByteArray?): GetLeaderboardResponse {
        val response = call.response
        if (!response.status.isSuccess()) {
            throwGetLeaderboardError(context, call, payload)
        }
        val builder = GetLeaderboardResponse.Builder()

        if (payload != null) {
            deserializeGetLeaderboardOperationBody(builder, payload)
        }
        builder.correctErrors()
        return builder.build()
    }
}

private fun throwGetLeaderboardError(context: ExecutionContext, call: HttpCall, payload: ByteArray?): kotlin.Nothing {
    val wrappedResponse = call.response.withPayload(payload)
    val wrappedCall = call.copy(response = wrappedResponse)

    val errorDetails = try {
        RestJsonErrorDeserializer.deserialize(call.response.headers, payload)
    } catch (ex: Exception) {
        throw ElasticLeaderboardException("Failed to parse response as 'restJson1' error", ex).also {
            setAseErrorMetadata(it, wrappedCall.response, null)
        }
    }

    val ex = when(errorDetails.code) {
        "ValidationException" -> ValidationExceptionDeserializer().deserialize(context, wrappedCall, payload)
        "NotFoundError" -> NotFoundErrorDeserializer().deserialize(context, wrappedCall, payload)
        else -> ElasticLeaderboardException(errorDetails.message)
    }

    setAseErrorMetadata(ex, wrappedResponse, errorDetails)
    throw ex
}

private fun deserializeGetLeaderboardOperationBody(builder: GetLeaderboardResponse.Builder, payload: ByteArray) {
    val deserializer = JsonDeserializer(payload)
    val HIGHSCORES_DESCRIPTOR = SdkFieldDescriptor(SerialKind.List, JsonSerialName("highScores"))
    val MAXENTRIES_DESCRIPTOR = SdkFieldDescriptor(SerialKind.Integer, JsonSerialName("maxEntries"))
    val NAME_DESCRIPTOR = SdkFieldDescriptor(SerialKind.String, JsonSerialName("name"))
    val OBJ_DESCRIPTOR = SdkObjectDescriptor.build {
        field(HIGHSCORES_DESCRIPTOR)
        field(MAXENTRIES_DESCRIPTOR)
        field(NAME_DESCRIPTOR)
    }

    deserializer.deserializeStruct(OBJ_DESCRIPTOR) {
        loop@while (true) {
            when (findNextFieldIndex()) {
                HIGHSCORES_DESCRIPTOR.index -> builder.highScores =
                    deserializer.deserializeList(HIGHSCORES_DESCRIPTOR) {
                        val col0 = mutableListOf<ScoreEvent>()
                        while (hasNextElement()) {
                            val el0 = if (nextHasValue()) { deserializeScoreEventDocument(deserializer) } else { deserializeNull(); continue }
                            col0.add(el0)
                        }
                        col0
                    }
                MAXENTRIES_DESCRIPTOR.index -> builder.maxEntries = deserializeInt()
                NAME_DESCRIPTOR.index -> builder.name = deserializeString()
                null -> break@loop
                else -> skipValue()
            }
        }
    }
}
