// Code generated by smithy-kotlin-codegen. DO NOT EDIT!

package kotlinconf.elasticleaderboard.serde

import aws.smithy.kotlin.runtime.serde.Deserializer
import aws.smithy.kotlin.runtime.serde.SdkFieldDescriptor
import aws.smithy.kotlin.runtime.serde.SdkObjectDescriptor
import aws.smithy.kotlin.runtime.serde.SerialKind
import aws.smithy.kotlin.runtime.serde.asSdkSerializable
import aws.smithy.kotlin.runtime.serde.deserializeList
import aws.smithy.kotlin.runtime.serde.deserializeMap
import aws.smithy.kotlin.runtime.serde.deserializeStruct
import aws.smithy.kotlin.runtime.serde.field
import aws.smithy.kotlin.runtime.serde.json.JsonDeserializer
import aws.smithy.kotlin.runtime.serde.json.JsonSerialName
import aws.smithy.kotlin.runtime.serde.serializeList
import aws.smithy.kotlin.runtime.serde.serializeMap
import aws.smithy.kotlin.runtime.serde.serializeStruct
import kotlinconf.elasticleaderboard.model.ScoreEvent

internal fun deserializeScoreEventDocument(deserializer: Deserializer): ScoreEvent {
    val builder = ScoreEvent.Builder()
    val SCORE_DESCRIPTOR = SdkFieldDescriptor(SerialKind.Integer, JsonSerialName("score"))
    val USER_DESCRIPTOR = SdkFieldDescriptor(SerialKind.String, JsonSerialName("user"))
    val OBJ_DESCRIPTOR = SdkObjectDescriptor.build {
        field(SCORE_DESCRIPTOR)
        field(USER_DESCRIPTOR)
    }

    deserializer.deserializeStruct(OBJ_DESCRIPTOR) {
        loop@while (true) {
            when (findNextFieldIndex()) {
                SCORE_DESCRIPTOR.index -> builder.score = deserializeInt()
                USER_DESCRIPTOR.index -> builder.user = deserializeString()
                null -> break@loop
                else -> skipValue()
            }
        }
    }
    builder.correctErrors()
    return builder.build()
}
